In [12]:
A=10
print(A)

10

The where function

In [13]:
#where()
np.where(logical test,
         value if True,
         value if False)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1725688639.py, line 2)

In [14]:
import numpy as np

In [ ]:
inventory=(12,102,10,0,0)
product=('fruits','vegetables','cereal','dairy','eggs')
inventory_array=np.array(inventory)
product_array=np.array(product)

In [ ]:
inventory_array

array([ 12, 102,  10,   0,   0])

In [ ]:
np.where(inventory_array<=0,"out of stock","in stock")

array(['in stock', 'in stock', 'in stock', 'out of stock', 'out of stock'],
      dtype='<U12')

In [ ]:
np.where(inventory_array<=0,product_array,"in stock")      #seeing the products name of out of stock

array(['in stock', 'in stock', 'in stock', 'dairy', 'eggs'], dtype='<U10')

In [ ]:
np.where(inventory_array<=0,"out of stock","in stock")

array(['in stock', 'in stock', 'in stock', 'out of stock', 'out of stock'],
      dtype='<U12')

In [ ]:
my_array=np.arange(20)

In [ ]:
np.where(my_array%2==0,"even","odd")

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [ ]:
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.where(my_array%2==0,"even",np.where(my_array==9,my_array,"odd"))

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       '9', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U21')

In [ ]:
numpy =numerical python,
Array Aggregation

In [ ]:
rng=np.random.default_rng()

In [ ]:
sales_array=rng.integers(0,100,10).reshape(2,5)
sales_array

array([[48, 63, 76,  6, 88],
       [54, 59, 46, 13, 51]])

In [ ]:
sales_array.sum(axis=0) #across rows upper lower sum in columns

array([102, 122, 122,  19, 139])

In [ ]:
sales_array.sum(axis=1) #row sum

array([281, 223])

In [ ]:
sales_array.sum() #as a whole

np.int64(504)

In [ ]:
sales_array.max()

np.int64(88)

In [ ]:
sales_array.mean()

np.float64(50.4)

In [ ]:
sales_array.min()

NameError: name 'sales_array' is not defined

In [ ]:
Ctrl + Shift + P (Cmd + Shift + P on Mac)
→ Type “Python: Select Language Server”
→ Choose “Pylance”

In [ ]:
sales_array.sort(axis=0)
sales_array                       #ascending arranged sort by column vertically

array([[48, 59, 46,  6, 51],
       [54, 63, 76, 13, 88]])

In [ ]:
sales_array.sort(axis=1)         #row wise ascending order horizontally
sales_array

array([[ 6, 46, 48, 51, 59],
       [13, 54, 63, 76, 88]])

In [ ]:
sales_array.sort()                        #by default it takes zero
sales_array

array([[ 6, 46, 48, 51, 59],
       [13, 54, 63, 76, 88]])

In [ ]:
np.median

NameError: name 'np' is not defined

In [ ]:
#pip install pandas
import pandas as pd

In [ ]:
PANDAS 
seRIES
DATAFRAME

In [16]:
import pandas as pd

d=("State":("AP","MP","HP"),
"Size":(10,20,30),
"Population":("High")

In [18]:
d={"state":["AP","UP","HP"],
   "size":[30,20,10],
   "population":["HIGH","HIGH","LOW"]}
pd.DataFrame(d)

  state  size population
0    AP    30       HIGH
1    UP    20       HIGH
2    HP    10        LOW

In [ ]:
sales=[0,5,155,0,518,0,1827,616,317,325]
Sales_series=pd.Series(sales,name="Sales")
Sales_series.index=["first","second","third","fourth","fifth","sixth","seven","eighth","nine","tenth"]
Sales_series

first        0
second       5
third      155
fourth       0
fifth      518
sixth        0
seven     1827
eighth     616
nine       317
tenth      325
Name: Sales, dtype: int64

In [ ]:
Sales_series.astype("float")

first        0.0
second       5.0
third      155.0
fourth       0.0
fifth      518.0
sixth        0.0
seven     1827.0
eighth     616.0
nine       317.0
tenth      325.0
Name: Sales, dtype: float64

In [ ]:
Sales_series.astype("bool")

first     False
second     True
third      True
fourth    False
fifth      True
sixth     False
seven      True
eighth     True
nine       True
tenth      True
Name: Sales, dtype: bool

In [ ]:
#series iNDEX naming ILOC and LOC

In [ ]:
sales=[0,5,155,0,510,0,1207,616,317,325]
month=["Jan","Feb","March",'April',"May","June","July","August","Sept","Oct"]
sales_month=pd.Series(sales,index=month,name="Sales")

NameError: name 'pd' is not defined

In [ ]:
sales_month

Jan          0
Feb          5
March      155
April        0
May        510
June         0
July      1207
August     616
Sept       317
Oct        325
Name: Sales, dtype: int64

In [ ]:
sales_month["Jan":"August"]

Jan          0
Feb          5
March      155
April        0
May        510
June         0
July      1207
August     616
Name: Sales, dtype: int64

In [ ]:
sales_month.iloc[0:8]

Jan          0
Feb          5
March      155
April        0
May        510
June         0
July      1207
August     616
Name: Sales, dtype: int64

In [ ]:
sales_month.loc["Jan":"August"]

Jan          0
Feb          5
March      155
April        0
May        510
June         0
July      1207
August     616
Name: Sales, dtype: int64

In [ ]:
#Resetting the index values

In [ ]:
sales_month.reset_index()

    index  Sales
0     Jan      0
1     Feb      5
2   March    155
3   April      0
4     May    510
5    June      0
6    July   1207
7  August    616
8    Sept    317
9     Oct    325

In [ ]:
sales_month.reset_index(drop=True)

0       0
1       5
2     155
3       0
4     510
5       0
6    1207
7     616
8     317
9     325
Name: Sales, dtype: int64

In [ ]:
sales_month[sales_month>510]

July      1207
August     616
Name: Sales, dtype: int64

In [ ]:
sales_month[(sales_month>510) | (sales_month==325)]                #we can use & and | for multile filters

July      1207
August     616
Oct        325
Name: Sales, dtype: int64

In [ ]:
sales_month[(sales_month<=616) & (sales_month>0)]

Feb         5
March     155
May       510
August    616
Sept      317
Oct       325
Name: Sales, dtype: int64

In [ ]:
sales_month.sort_values() #by default ascending order values

Jan          0
April        0
June         0
Feb          5
March      155
Sept       317
Oct        325
May        510
August     616
July      1207
Name: Sales, dtype: int64

In [ ]:
sales_month.sort_values(ascending=False)   #Decending order  values

July      1207
August     616
May        510
Oct        325
Sept       317
March      155
Feb          5
Jan          0
June         0
April        0
Name: Sales, dtype: int64

In [ ]:
sales_month

Jan          0
Feb          5
March      155
April        0
May        510
June         0
July      1207
August     616
Sept       317
Oct        325
Name: Sales, dtype: int64

In [ ]:
sales_month.sort_values(ascending=False,inplace=True)
sales_month

July      1207
August     616
May        510
Oct        325
Sept       317
March      155
Feb          5
Jan          0
June         0
April        0
Name: Sales, dtype: int64

In [ ]:
sales_month.sort_index()                    #index ascending

April        0
August     616
Feb          5
Jan          0
July      1207
June         0
March      155
May        510
Oct        325
Sept       317
Name: Sales, dtype: int64

In [ ]:
sales_month.sort_index(ascending=False)             #Index descending

Sept       317
Oct        325
May        510
March      155
June         0
July      1207
Jan          0
Feb          5
August     616
April        0
Name: Sales, dtype: int64

In [ ]:
#Arithmetic operations

In [ ]:
#Aggregation
oil= pd.read_csv("C:/Users/ekarm/Downloads/oil.csv")
#oil=pd.read_csv("oil.csv")   #same jupyter notebook

In [ ]:
oil

            date  dcoilwtico
0     2013-01-01         NaN
1     2013-01-02       93.14
2     2013-01-03       92.97
3     2013-01-04       93.12
4     2013-01-07       93.20
...          ...         ...
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

[1218 rows x 2 columns]

In [ ]:
import numpy as np

In [ ]:
oil_array=np.array(oil["dcoilwtico"])
oil_series=pd.Series(oil_array,name = "Oil_prices")
oil_series

0         NaN
1       93.14
2       92.97
3       93.12
4       93.20
        ...
1213    47.65
1214    46.40
1215    46.46
1216    45.96
1217    47.26
Name: Oil_prices, Length: 1218, dtype: float64

In [ ]:
oil_series

0         NaN
1       93.14
2       92.97
3       93.12
4       93.20
        ...
1213    47.65
1214    46.40
1215    46.46
1216    45.96
1217    47.26
Name: Oil_prices, Length: 1218, dtype: float64

In [ ]:
oil_series.isna().sum()   # null values and thei sum

np.int64(43)

In [ ]:
oil_series.value_counts()

Oil_prices
96.44    4
47.72    4
47.65    4
93.12    4
46.02    4
        ..
97.65    1
97.46    1
92.97    1
93.14    1
47.26    1
Name: count, Length: 998, dtype: int64

In [ ]:
oil_series.mean()

np.float64(67.71436595744682)

In [ ]:
oil_series.dropna().isna().sum()

np.int64(0)

In [ ]:
oil_series.fillna(67).value_counts()

Oil_prices
67.00    43
96.44     4
46.02     4
47.72     4
47.65     4
         ..
94.28     1
94.12     1
94.27     1
93.98     1
45.66     1
Name: count, Length: 999, dtype: int64